GET http://localhost:5000/api/clubs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIwNWM2MTEzMDI3MjU4OWFlYTkwOGQiLCJyb2xlIjoiY2x1Yl9hZG1pbiIsImlhdCI6MTc1NjQxOTQ5NywiZXhwIjoxNzU2NTA1ODk3fQ.Ey-CrqpC2dEOA56OKI2XmokwmeNTOm56v_67umCeHPM

###
GET http://localhost:5000/api/clubs/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIwNWM2MTEzMDI3MjU4OWFlYTkwOGQiLCJyb2xlIjoiY2x1Yl9hZG1pbiIsImlhdCI6MTc1NjQxOTQ5NywiZXhwIjoxNzU2NTA1ODk3fQ.Ey-CrqpC2dEOA56OKI2XmokwmeNTOm56v_67umCeHPM
###
POST http://localhost:5000/api/clubs/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIwNWM2MTEzMDI3MjU4OWFlYTkwOGQiLCJyb2xlIjoiY2x1Yl9hZG1pbiIsImlhdCI6MTc1NjQxOTQ5NywiZXhwIjoxNzU2NTA1ODk3fQ.Ey-CrqpC2dEOA56OKI2XmokwmeNTOm56v_67umCeHPM
Content-Type: application/json

{
    "role": "member",
    "userId": "68b05d2b130272589aea90aa",
    "clubId": "68b09872e05530585f80e30b"
}

###
GET http://localhost:5000/api/announcements
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OGIwNWQyYjEzMDI3MjU4OWFlYTkwYWEiLCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTc1NjQ1NTA0NCwiZXhwIjoxNzU2NTQxNDQ0fQ.rmkks_h5SECNxKN2UvkavXBRy0exR9HvsRZa-9wHlmo
